### PR TITLE
Added abv values to the file src/data/ingredient-data.ts and more

### PR DESCRIPTION
**Pull request by soil8rino**
src/data/ingredient-data.ts

Also I have left many commented wikipedia links to the various ingredients for future reference

Modified also

src/locales/it/translation.json

to current Italian

### CODE REVIEW

**Comment by anton-gustafsson** [comment]
Thank you for the PR! Great job.

I noticed that the comments were backslash and not forward slash. I made a commit fixing it so it should be working.

Lets me know when this is ready to merge 🚀

**Comment by soil8rino** [comment]
My fault. What should I do now

**Comment by anton-gustafsson** [comment]
No worries! It is fixed.

Have you added abv for all alcoholic ingredients? 

If so, I would love to merge this. I'm just dubble checking you are done

**Comment by anton-gustafsson** [comment]
Thank you for the list! I will try to add abv values for the rest

**Pull request merged**
