### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by YottaMxt**
Hi, so there's my Spanish translation, I hope you like it. I expect to do another translation to another language.

### CODE REVIEW

**Comment by anton-gustafsson** [comment]
Thanks! Looks great. Will merge this soon

**Comment by YottaMxt** [comment]
> Thanks! Looks great. Will merge this soon
> 
> What other language? Just curious :)

It'll be Catalan.

**Comment by YottaMxt** [comment]
> > Thanks! Looks great. Will merge this soon
> > What other language? Just curious :)
> 
> It'll be Catalan.

Actually, it'd be nice if you could wait till tomorrow to merge the pull request, tomorrow I'll probably send the Catalan translation, so you can merge it all in one.

**Comment by anton-gustafsson** [comment]
Yes I will wait, take your time. Thank you for this

I just released a feature where you can translate the ingredients as well. It is optional but appreciated. 
There is info about this in the README.md

**Comment by anton-gustafsson** [comment]
@YottaMxt Let me know when I can merge this 🚀

**Comment by YottaMxt** [comment]
> @YottaMxt Let me know when I can merge this 🚀

Only the Catalan translation of ingredients is incomplete.

**Pull request merged**
